### ISSUE TITLE
Entity API: next and previous revision attributes

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#108]

**Comment by yuanzhou** [comment]
![92ED56D6-DE79-4CE0-BCE3-BC6CA3E7777B](https://user-images.githubusercontent.com/195873/107998516-51f87a80-6fb3-11eb-8330-892e134cf906.jpeg)

**Comment by shirey** [comment]
@yuanzhou Per Jonathan change the names of the attributes from previous_version and next_version to previous_revision and next_revision.

**Comment by yuanzhou** [comment]
I'll change them in entity-api, also the mapping in search-api to use these new names in ES.
