### ISSUE TITLE
protocols.io DOI is a required field for Donor and Sample

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#123]
The protocols.io DOI URL field should be a required field on both Donor and Sample

**Comment by yuanzhou** [comment]
They are required in entity-api. 
For new Donor creation:
````
{
    "error": "400 Bad Request: Missing required keys in request json: protocol_url"
}
````

And for new Sample creation:
````
{
    "error": "400 Bad Request: Missing required keys in request json: specimen_type, protocol_url, direct_ancestor_uuid"
}
````

**Comment by yuanzhou** [comment]
Addressed the issue with adding empty value check on the required keys during POST.
