### ISSUE TITLE
Expose image uploads via assets service

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#128]
- Create a symlinks to file uploads into the assets directory
- Add auth checks to the auth service for file ids

**Comment by shirey** [comment]
@yuanzhou Per our discussion the other day, these links into the assets space should be linked by the "file uuid directory"

In addition to links for the files attached to Datasets, this should happen for all uploads against Donors or Samples too.  Possible the linkage into assets space should generally be in the "commit" method that takes the temporary file and commits the file to permanent storage and generates the uuid?

**Comment by yuanzhou** [comment]
Updates:
- The symlink from uploaded file to the assets is handled by https://github.com/hubmapconsortium/ingest-api/pull/76
- Auth checks for file uuid via assets is handled in gateway: https://github.com/hubmapconsortium/gateway/pull/104
