### ISSUE TITLE
Move file upload functioality to ingest-api

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#129]
- Move the following functions from entity-api//file-upload/ method to entity api
- Create ingest-api /file-commit/<file-uuid> and ingest-api/file-remove/<file-uuid> which have the functionality of the ingest-api.file_upload_helper.commit_file and ingest-api.file_upload_helper.remove_file methods
- In the triggers for POST/PUT calls for attributes *_files_to_add and *_files_to_delete, make calls to the new ingest-api/file-commit/remove methods

**Comment by yuanzhou** [comment]
Changes made in entity-api, ingest-api, and gateway in drafts:
- https://github.com/hubmapconsortium/entity-api/pull/181
- https://github.com/hubmapconsortium/ingest-api/pull/55
- https://github.com/hubmapconsortium/gateway/pull/96

Waiting on the corresponding change in ingest-ui: https://github.com/hubmapconsortium/ingest-ui/issues/428 before we can test on DEV.
