### ISSUE TITLE
need to expand API (and data models?) for attribution

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/entity-api#13]
This is in reference to https://github.com/hubmapconsortium/portal-ui/issues/36. 

We will need to be able to distinguish data sets produced by different consortia/projects (e.g. HuBMAP, HCA, HTAN) as we might load some of their data in the future. A field called "project" would be useful for that purpose. This can just be a string.

Furthermore, we should be able to link data sets and other entities to NIH awards and would need a field to retrieve award numbers. 

For TMCs/lab we should also be able to get a contact email address so that data consumers can reach out to the data producer. 

In general, we need to be able to distinguish between different labs within a TMC as well. Some TMCs produce different data types in different labs with different investigators.

**Comment by yuanzhou** [comment]
I don't think this is still relevant.
