### ISSUE TITLE
Avoid multiple layers of serialized JSON wrapping

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/entity-api#14]
As I'm getting in the actual API, I'm seeing lots of places where a JSON response includes serialized JSON as a string. For example in `/entities/{uuid}/provenance`, the response looks like:
```json
{"provenance_data": "{...}"}
```
When I deserialize that, I get
```json
{
  "entity": {
  "hubmap:entities/13ceb39891c4d06fc8fb5dbb5b0c16a0": {
      "hubmap:metadata": "{...}"
```
... and when I deserialize *that*:
```json
{"protocols": "[{\"protocol_file\":...}
```

Multiple layers of serialization
- Make it impossible to really describe the response in detail in JSON schema.
- Force the client to do all this deserialization, and force error handling deeper in the code.
- Make it impossible to use normal pretty-printing utilities.

For now, if I need this data, I'll be deserializing it myself, so please don't change it in existing API endpoints, but I think it should change over time.

**Comment by shirey** [comment]
@yuanzhou Please verify that this is no longer the case in the new/refactored version of entity-api.

**Comment by yuanzhou** [comment]
No longer the case in the refactored entity-api. In general entity retrieval, we get back json array or json object directly. No more json-as-string. For the provenance call, the PROV package only puts hashable types as provenance attribute values. Thus those json array and json objects won't be exposed via the /provenance call.

**Comment by shirey** [comment]
I believe this has been taken care of during a major refactoring effort a while ago.  @mccalluc If you're still seeing this let us know where.
