### ISSUE TITLE
Remove "/entities/samples"

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/entity-api#15]
The api endpoint `/entities/samples` replies with `[]`, while `/entities/types/samples` returns a lot of results.
* Is `/entities/samples` vestigial, or do you have some plan for it?

**Comment by cborromeo** [comment]
@mccalluc it is vestigial.  @shirey should I remove it as part of 1.6?

**Comment by shirey** [comment]
If we no longer need it go ahead and remove it.

**Comment by cborromeo** [comment]
OK, I'll remove it from 'master' instead of all the branches.  Does that sound correct?

**Comment by shirey** [comment]
No, as you suggest above, change it in the eventual 1.6 release branch to release then.

**Comment by cborromeo** [comment]
/entities/sample endpoint only exists in the entity-api project.  So it is not part of the ingest-api 1.6 changes.  I made a branch called chuck-api-pruning and stored the changes there.

**Comment by mccalluc** [comment]
@cborromeo : I don't see a `chuck-api-pruning` branch now: Can you reference the PR that merged it (if that's what happened) and close?

**Comment by cborromeo** [comment]
@mccalluc I pushed the branch.

**Comment by mccalluc** [comment]
Reopening: The SmartAPI referenced from the current README still has [`/entities/samples`](http://smart-api.info/ui/12af775769ba65a684476960f5f87e72#/entity/getEntityBySampleType).

My sense is that the API is still evolving, and that keeping the docs in step with what we actually offer is not a priority. That is ok, really: I just think we should be honest about it, and file an issue to fill in the API docs at the end, rather than claiming that what we have now would be useful to anyone outside. (Filling in details about response structure is another part of the task.) Your call.

**Comment by cborromeo** [comment]
@mccalluc @shirey I was able to update the Data Ingest API on the SmartAPI interface.  However, there is still an older version of "HuBMAP Entity APIs".  I cannot get this one removed and the contact email for SmartAPI just bounces.

**Comment by shirey** [comment]
We need to figure out how to remove the old version from SmartAPI.  Emails sent to SmartAPI folks, awaiting answer.

**Comment by cborromeo** [comment]
@mccalluc Can you check the updated versions of the APIs on SmartAPI: https://smart-api.info/registry?q=hubmap.  I removed the old versions of the files.  This should represent the current APIs.

**Comment by mccalluc** [comment]
Looks good.
