### ISSUE TITLE
Add dataset lab id field

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#152]
- entity-api add attribute Dataset.lab_dataset_id, copy existing values of Dataset.title to lab_dataset_id
 - search-api add lab_dataset_id to indices
 - ingest-ui on Dataset form change field "Dataset Name" to "Lab Name or ID" and tie it to the new lab_dataset_id attribute (instead of title)

**Comment by yuanzhou** [comment]
Would this be a good chance to change Donor.label to Donor.lab_name too in entity-api? Currently in search-api mapping: https://github.com/hubmapconsortium/search-api/blob/test-release/src/elasticsearch/neo4j-to-es-attributes.json#L90 so this would not affect the search results. Not sure if ingest-ui would need the corresponding tweaks.

**Comment by yuanzhou** [comment]
Hold off for now

**Comment by yuanzhou** [comment]
Added search-api index mapping: https://github.com/hubmapconsortium/search-api/commit/fab4616a66d7b9454b5f14f9fac462a0687a6b1f

**Comment by yuanzhou** [comment]
Added `Dataset.lab_dataset_id` definition: https://github.com/hubmapconsortium/entity-api/pull/183

**Comment by yuanzhou** [comment]
Will need @davism84 or @BirdMachine's help with the ingest-ui changes. Per Bill's comment:

> For lab_dataset_id you can remove the required validation from the UI.

**Comment by yuanzhou** [comment]
> copy existing values of Dataset.title to lab_dataset_id

Will need to execute this Cypher query in Neo4j:
````
MATCH (n:Dataset) 
WHERE n.title IS NOT NULL
SET n.lab_dataset_id=n.title
RETURN n.title, n.lab_dataset_id
````

**Comment by yuanzhou** [comment]
Will also need to trigger a reindex to get this new filed into ES. The ingest-ui displays the table view by pulling information from search-api.
