### ISSUE TITLE
Refactor ID attribute names to match the types of IDs stored

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/entity-api#17]
With portal-ui pointing at https://entity-api.test.hubmapconsortium.org, visit
http://localhost:5000/browse/sample/13ceb39891c4d06fc8fb5dbb5b0c16a0

The response includes:

field | value
-- | --
reference_uuid | ['13ceb39891c4d06fc8fb5dbb5b0c16a0']
source_uuid | HBM:844-QSHB-647

- The first is JSON wrapping a UUID. I'd prefer not to have the wrapping (see #14)... but if we do have it, the field name should reflect the contents.
- The second is a DOI suffix.

**Comment by shirey** [comment]
We'll do an analysis of the attribute naming for storage and retrieval for all id fields-
Anything that stores a 32 digit uuid should be named like *_uuid.  Anything that stores a DOI suffix should be named doi_suffix and display ids (like XXXX000#-XX-#-# should be named display_id.

This will affect ingest_ui as well.

Changing the name of this issue to make it more general.

**Comment by cborromeo** [comment]
@shirey which branch should this go into?

**Comment by shirey** [comment]
Let's create a version branch.  Next version will be, what-  1.1? we'll need to make changes to and extensively test with ingest and Chuck M. will need to change/test against his stuff before releasing.

**Comment by shirey** [comment]
The original intent of the task was based on some issues Chuck M. was having.  We'll just suppress the field in question from Entity and Search API returns as it is only needed for the ingest ui, for now.  And hold this task for a later date.

**Comment by shirey** [comment]
Closing.  This was finished a while ago under a different issue.
