### ISSUE TITLE
Consistency in UUID presentation

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/entity-api#20]
The fields `provenance_user_sub` and `user_group_uuid` use dashes; URLs and the `uuid` field do not.

Consistency would be good: No strong preference between the two.

(Redirection from a non-preferred to a preferred form (either in API or portal) is an option, but it's not my preference.)

**Comment by ngehlenborg** [comment]
Here's a real-life example: https://portal.test.hubmapconsortium.org/browse/sample/77e7bcdacbecba17dfb674cf1fc0c5ba

According to RFC4122 the string representation of UUIDs contain hyphens. I would suggest that we follow that for readability: https://tools.ietf.org/html/rfc4122#section-3

**Comment by yuanzhou** [comment]
No longer relevant.
