### ISSUE TITLE
allow PUT for public Samples

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#210]
This is a temporary measure to allow users to enter RUI/location information for published/public entities.  This will be reverted at the end of September.

On a Sample update (PUT) for samples which are public (ancestors of published datasets) allow edits.

**Comment by yuanzhou** [comment]
Currently there's no validation at all on the Sample update via PUT. 

What is the definition of a public Sample? For Dataset and Upload, we use `status` attribute.

**Comment by yuanzhou** [comment]
Update: nothing needs to be done with entity-api to address this issue.
