### ISSUE TITLE
GET doesn't have `next_revision_uuid` field

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#212]
On DEV doing a GET against dataset `abc01ead645d7a6f9c19ea99b26e38df` should yield a `next_revision_uuid` of `e6d393366887f95226acf0e659134e29`, but doesn't

**Comment by yuanzhou** [comment]
The reason why `abc01ead645d7a6f9c19ea99b26e38df` (published status) doesn't return `next_revision_uuid` is because its next revision `e6d393366887f95226acf0e659134e29` is not published (QA status). Entity-API only returns `next_revision_uuid` if this next revision dataset is published.
