### ISSUE TITLE
Remove all test data from PROD

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/entity-api#23]
My understanding is that the API is currently returning data from a recent snapshot of the DB. It contains a lot of records like "Bill's test entity": Will these be removed at some point? Or will there be some extra flag for curation stage, and we'll use that to hide these? Or something else?

**Comment by mccalluc** [comment]
Will be talked about 1/17 hive tech meeting, maybe..

**Comment by shirey** [comment]
Remove all test data from PRODUCTION.

**Comment by shirey** [comment]
@cborromeo This includes all entities attached to IEC-Testing all additionally all Collections that are only attached to the other deleted entities (orphaned collections).

**Comment by cborromeo** [comment]
This query returns all data associated with the Testing Group: MATCH (e)-[*]->(children) WHERE e.displayname = 'IEC Testing Group' RETURN children

That should be a good start.
