### ISSUE TITLE
Rename current Ontology-API endpoints

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/entity-api#230]
From Jonathan: That reminds me some of the APIs need slight changes in naming - I think he has ‘description’ in a number of places that should be ‘term’

**Comment by yuanzhou** [comment]
Is this still relevant? We had archived the old  "hubmapconsortium/ontology-api" repo and migrated to use the "x-atlas-consortia/ubkg-api".

**Comment by ChuckKollar** [comment]
It would appear that this is very old (Sep 23, 2021), and I would think no longer relevant.
