### ISSUE TITLE
add `lab_dataset_id` to response in `prov_info`

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#277]
Add to the response for all `/prov_info/` calls an  additional field/column dataset.lab_dataset_id as lab_id_or_name

**Comment by DerekFurstPitt** [comment]
dataset.lab_dataset_id is already included [per issue 263](https://github.com/hubmapconsortium/entity-api/issues/263#:~:text=dataset_lab_id,the%20data%20provider) and is called "dataset_lab_id". Does this refer to something different?
