### ISSUE TITLE
Create another example Jupyter Notebook to:

### ISSUE THREAD

**Issue by DerekFurstPitt** [hubmapconsortium/entity-api#302]
retrieve a globus token and use with the sdk to get non-public versions of the results. Look for globus jupyter notebook for reference

**Comment by shirey** [comment]
@DerekFurstPitt An idea for this is to define a set of data using the Cells API for an interesting case, then use our APIs to get provenance info and display (maybe graphs?).  Possibly we can use the [Cells API Python Interface](https://github.com/hubmapconsortium/hubmap-api-py-client).

@mruffalo or @sfd5311 have said that they would help with Cells API usage and define a good query.
From Matt and Sean:
Matt Ruffalo to Everyone (10:19 AM)
I'm sure there are additional queries that might be of biological interest which would be great to showcase
Sean Donahue to Everyone (10:20 AM)
That's right.  I actually have some examples of Cells queries using the client interoperating with the Search API in a way similar to what you described.
Can get you those/go over them with you some time if you like, Bill
Matt Ruffalo to Everyone (10:20 AM)
Like "find cells with this interesting expression patterns, find datasets containing those cells, investigate donor demographics for those vs. other HuBMAP donors"
Of course "this interesting expression pattern" can mean *many* different things
Sean Donahue to Me (Direct Message) (10:28 AM)
The notebooks I've been working on are in colab, though, so I'd have to share them with you on there.
