### ISSUE TITLE
Improve performance of Entity retrieval, creation, and update

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#316]
We've been seeing some major timeout issues due to performance of retrieving single entities from the Entity API.  It appears as though a lot of time is spent retrieving information from Neo4j during various `on_read_trigger` events.  This has been an issue during "full reindexes" when a lot of entities are read at one time, during dataset reorganization and processing and during the retrieval of an Upload entity that has a lot of associated Datasets.

One way to replicate the problem is to GET the following Upload on PROD:
`/entities/9667fe740e53ed0af2e85ec4d358e0f1`

**Comment by shirey** [comment]
The attached profiling efforts were done
[zhou-profiling.txt](https://github.com/hubmapconsortium/entity-api/files/8350500/zhou-profiling.txt)
![call-graph-get-9667fe740e53ed0af2e85ec4d358e0f1-upload](https://user-images.githubusercontent.com/5816400/160121431-771da532-d37c-4093-ad9f-f5176e127030.png)
[prof-get-9667fe740e53ed0af2e85ec4d358e0f1-upload.txt](https://github.com/hubmapconsortium/entity-api/files/8350509/prof-get-9667fe740e53ed0af2e85ec4d358e0f1-upload.txt)
.

**Comment by yuanzhou** [comment]
Testing and profiling https://github.com/hubmapconsortium/entity-api/issues/308#issuecomment-1078632517

**Comment by yuanzhou** [comment]
Turned out the performance issue caused by the fact that we are returning the list of normalized dataset dicts for the given upload. Changing to return dataset uuids drastically improves the performance (from 51 seconds to 2 seconds). Also noticed the same for Collection and made the same change. https://github.com/hubmapconsortium/entity-api/pull/318

Correspondingly, tweaks made in search-api https://github.com/hubmapconsortium/search-api/pull/471

**Comment by yuanzhou** [comment]
Also drastically improved the query performance on getting `Dataset.title` via https://github.com/hubmapconsortium/entity-api/commit/da46c4df620f095be81d7b3d07890c568accf1ec

**Comment by yuanzhou** [comment]
AB test within the entity-api container on PROD after deploying the above changes:
```
[root@entity-api app]# ab -c 500 -n 5000 -s 90 http://localhost:8080/entities/51c8c96154b5a5eaab69d6e7b565a853
This is ApacheBench, Version 2.3 <$Revision: 1430300 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 500 requests
Completed 1000 requests
Completed 1500 requests
Completed 2000 requests
Completed 2500 requests
Completed 3000 requests
Completed 3500 requests
Completed 4000 requests
Completed 4500 requests
Completed 5000 requests
Finished 5000 requests


Server Software:        nginx/1.21.6
Server Hostname:        localhost
Server Port:            8080

Document Path:          /entities/51c8c96154b5a5eaab69d6e7b565a853
Document Length:        6273 bytes

Concurrency Level:      500
Time taken for tests:   93.154 seconds
Complete requests:      5000
Failed requests:        2106
   (Connect: 0, Receive: 0, Length: 2106, Exceptions: 0)
Write errors:           0
Non-2xx responses:      2106
Total transferred:      20156810 bytes
HTML transferred:       18484704 bytes
Requests per second:    53.67 [#/sec] (mean)
Time per request:       9315.414 [ms] (mean)
Time per request:       18.631 [ms] (mean, across all concurrent requests)
Transfer rate:          211.31 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    2   5.5      0      24
Processing:     0 8016 15891.6   2690   76053
Waiting:        0 8016 15891.6   2690   76053
Total:          0 8018 15893.2   2690   76068

Percentage of the requests served within a certain time (ms)
  50%   2690
  66%   2956
  75%   3186
  80%   3504
  90%  25955
  95%  60005
  98%  60007
  99%  60011
 100%  76068 (longest request)
```

And from my local:
```
[zhy19@fedora HuBMAP]$ ab -c 500 -n 5000 -s 90 https://entity.api.hubmapconsortium.org/entities/51c8c96154b5a5eaab69d6e7b565a853
This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking entity.api.hubmapconsortium.org (be patient)
Completed 500 requests
Completed 1000 requests
Completed 1500 requests
Completed 2000 requests
Completed 2500 requests
Completed 3000 requests
Completed 3500 requests
Completed 4000 requests
Completed 4500 requests
Completed 5000 requests
Finished 5000 requests


Server Software:        nginx/1.21.6
Server Hostname:        entity.api.hubmapconsortium.org
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES128-GCM-SHA256,2048,128
Server Temp Key:        ECDH P-256 256 bits
TLS Server Name:        entity.api.hubmapconsortium.org

Document Path:          /entities/51c8c96154b5a5eaab69d6e7b565a853
Document Length:        6273 bytes

Concurrency Level:      500
Time taken for tests:   60.757 seconds
Complete requests:      5000
Failed requests:        3513
   (Connect: 0, Receive: 0, Length: 3513, Exceptions: 0)
Non-2xx responses:      3513
Total transferred:      12926015 bytes
HTML transferred:       9850144 bytes
Requests per second:    82.29 [#/sec] (mean)
Time per request:       6075.711 [ms] (mean)
Time per request:       12.151 [ms] (mean, across all concurrent requests)
Transfer rate:          207.76 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       22  127 185.7     57     828
Processing:    12 3961 7780.3     56   29207
Waiting:        8 3954 7781.8     43   29201
Total:         37 4088 7847.6    158   29861

Percentage of the requests served within a certain time (ms)
  50%    158
  66%   2791
  75%   4013
  80%   5240
  90%  15381
  95%  29046
  98%  29480
  99%  29780
 100%  29861 (longest request)
```

**Comment by yuanzhou** [comment]
Made further improvements (via PR #327) to exclude properties with time-consuming read triggers on POST and PUT resulting json. 
```
if normalized_entity_type == 'Sample':
    properties_to_skip = [
        'direct_ancestor'
    ]
elif normalized_entity_type == 'Dataset':
    properties_to_skip = [
        'direct_ancestors',
        'collections',
        'upload',
        'title', 
        'previous_revision_uuid', 
        'next_revision_uuid'
    ]
elif normalized_entity_type in ['Upload', 'Collection']:
    properties_to_skip = [
        'datasets'
    ]
```
and we can also get back all properties by using the query string like what Joel asked for:

```
POST: /entities/<entity_type>?return_all_properties=true
PUT: /entities/<id>?return_all_properties=true
```

Per @shirey 's suggestion:
> I’d be curious to put this on STAGE and run, in a “loop”, the creation/POST of 1000 datasets, then a loop to update those 1000 datasets.

I conducted load testing https://github.com/hubmapconsortium/entity-api/blob/yuanzhou/load-test/load_test/load_test.py to benchmark the changes with Before/After comparison using 1000 POST/PUT and 250 POST/PUT respectively. Results attached. With excluding those fields, more POST/PUT calls made through.
[250-after.log](https://github.com/hubmapconsortium/entity-api/files/8376922/250-after.log)
[250-before.log](https://github.com/hubmapconsortium/entity-api/files/8376923/250-before.log)
[1000-after.log](https://github.com/hubmapconsortium/entity-api/files/8376924/1000-after.log)
[1000-before.log](https://github.com/hubmapconsortium/entity-api/files/8376925/1000-before.log)
