### ISSUE TITLE
Collection creation endpoint

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#353]
Create a POST/PUT endpoints to create and edit Collections.

Create these within the existing `enity-api` general framework which is controlled by the [provenance_schema.yaml file](https://github.com/hubmapconsortium/entity-api/blob/main/src/schema/provenance_schema.yaml)

**Comment by yuanzhou** [comment]
Duplicate of https://github.com/hubmapconsortium/entity-api/issues/466 and had been addressed.
