### ISSUE TITLE
UUID in Elasticsearch is 404s in EntityAPI

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/entity-api#38]
This UUID is in Elasticsearch but is not in in the Entity API:

```
$ curl -i -H "Content-Type: application/json" -H "Authorization: Bearer ......." https://entity-api.test.hubmapconsortium.org/entities/fd1c1ab4890f527704b20de52b797551/provenance
HTTP/1.1 404 NOT FOUND
Server: nginx/1.17.9
Date: Thu, 23 Apr 2020 22:05:14 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 74
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
Access-Control-Allow-Headers: DNT,User-Agent,Authorization, MAuthorization,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
Access-Control-Expose-Headers: Content-Length,Content-Range

unable to find information on identifier: fd1c1ab4890f527704b20de52b797551
```

(I am looking at this particular record because it's the one example I've been assured has related files.)

My assumption is that I need to make my code robust against this kind of failure? Do you want notifications when this happens, or will your monitor your own logs for 404s?

**Comment by shirey** [comment]
The files all seem to be missing for ALL of the pipeline derived datasets on DEV.
When the files are there, they can be accessed via the file service.
The algorithm to construct the url is:  make a url/path by concatenating the file service server url with the dataset id with the relative path to the file…  

https://assets.dev.hubmapconsortium.org/fd1c1ab4890f527704b20de52b797551/src_data/segmentation.json 

This call will require an authorization header with a Globus Nexus token.

The file service servers/urls are:
  DEV: https://assets.dev.hubmapconsortium.org
  TEST: https://assets.test.hubmapconsortium.org
  PROD:   https://assets.hubmapconsortium.org
