### ISSUE TITLE
Remove `tissue_type` calculated field

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#416]
The `tissue_type` field is calculated on a GET from the old `specimen_type` field.  Remove the `tissue_type` field as it has been directly replaced by `sample_category`.

**Comment by yuanzhou** [comment]
We had migrated to use `Sample.sample_category` field in entity-api/ingest-ui/search-api/ingest-api. The old fields `tissue_type` and `specimen_type` are still in the schema yaml file. Should be completed removed.

**Comment by yuanzhou** [comment]
https://github.com/hubmapconsortium/entity-api/issues/569
