### ISSUE TITLE
Immediate ancestor and descendant returned with an entity

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#44]
for entity-api  /entities/<id>  add the additional fields in the returned object:

   immediate_ancestors []
   immediate_descendants[]

**Comment by cborromeo** [comment]
@shirey which branch?

**Comment by cborromeo** [comment]
@shirey I will add those fields to the data returned by these GET calls:
/entities
/entities/types/<type_code>
/entities/<identifier>
/entities/uuid/<uuid>

**Comment by cborromeo** [comment]
@shirey This is an example of a typical node:
![Screenshot from 2020-05-18 12-33-45](https://user-images.githubusercontent.com/5503816/82237619-f30eb380-9903-11ea-82d0-14910139849f.png)  
The orange nodes are entities.  The blue nodes are metadata nodes.  The red nodes are activities.  The elevated orange node in the middle is the "current" entity we are returning. 

I just want to verify my logic with you: I am only going to return a list of entity nodes, plus their metadata.  I am not returning the activity nodes.  In this example, the ancestor node is the orange node on the left whereas the descendant node is the orange one on the right.

**Comment by cborromeo** [comment]
the cypher will look something like this:

MATCH (anc_meta)<-[:HAS_METADATA]-(ancestor)-[r2]->(ancestor_act)-[r1]->(target)-[r3]->(descendant_act)-[r4]->(descendant)-[:HAS_METADATA]->(desc_meta) WHERE target.uuid = '9046d09943f6a10b70544822de1d5752' RETURN target, ancestor, anc_meta, descendant, desc_meta
