### ISSUE TITLE
Change PUT status validation

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#453]
Currently a PUT to change the `status` of a Dataset is validated to make sure that it has the extra `X-Hubmap-Application` header.  Change this such that:
  - only the change to `status == Published` requires the `X-Hubmap-Application` header (all other status changes allowed except below...).
  - if the status is currently set to Published (`status == Published`) then don't allow any change to the `status` field at all

The same validation rules should be used for `Publication` entities as well.

**Comment by shirey** [comment]
Closing as this has been implemented.

**Comment by yuanzhou** [comment]
@shirey I confirmed in the code that this card had been addressed properly.
