### ISSUE TITLE
Dataset status update issue, possibly related to caching

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/entity-api#489]
Joel ran into strange `Dataset.status` update issue:
>I'm passing on to you a problem I just encountered and reported to Bill.  He said you might check the entity-api logs.  The error description was:

>... different issue, and a stranger one: I have a transaction with entity-api at 4:16 Jun 8 setting the status of a3c670c9113d269a0ea60f52e0b90204 to Error.  I see the reply to the transaction, in which the new status is listed as 'Error'.  It continued to appear New in the Portal, even after I sent a reindex, so I asked entity-api for its status .  Entity-api now says the status is New, as if the earlier transaction hadn't happened.  Did a transaction between entity-api and Neo4J somehow get lost?

>I did issue a reindex, but more importantly I asked entity-api directly for its status after the response said it was being set to Error, and the status it reported back was New.

**Comment by yuanzhou** [comment]
I just checked. Entity-api returns Error status, but portal-ui says New:
 
![image](https://github.com/hubmapconsortium/entity-api/assets/195873/05b00bb4-7102-4770-83a7-1b3fc269fd7c)
![image](https://github.com/hubmapconsortium/entity-api/assets/195873/cb445aea-60db-4838-a49a-2cf4cdcedb36)

Then I updated the dataset via a PUT call, just to trigger the reindex, and I've removed the updated value from Neo4j. Now it shows as Error on portal-ui

![image](https://github.com/hubmapconsortium/entity-api/assets/195873/ef15a336-c405-460c-b91e-4d10309047ab)

My guess is for some reason the PUT call didn't clear the previous cache or it failed to do so, or something going on with the memcache server, that' why portal-ui still used the old status. BUT this should not happen.
The PUT call I issue this afternoon did go through correctly and cleared the cache. Please report back if you ever this the similar issue. I believed it's related to the memcache.

From Joel:
>You should have a conversation about this with Sunset- he tells me a problem matching this one is intermittent but common.

**Comment by yuanzhou** [comment]
I did notice this
![image](https://github.com/hubmapconsortium/entity-api/assets/195873/5f06edc0-2821-4b5f-b0f2-fdb27668b73f)

**Comment by yuanzhou** [comment]
Something could be related, reported by Sunset:
>example: a derived dataset is created and status is updated to QA. Ingest-UI shows QA, Portal shows Processing. A PUT call on https://search.api.hubmapconsortium.org/v3/reindex/<uuid> fixes that

>a similar thing has happened for some dataset visualizations (not showing them because of missing metadata). The same call fixes the issue

**Comment by sunset666** [comment]
Per Bill's request. We have 3 calls that sets statuses through entity-api using basically the following json:

PUT https://entity.api.hubmapconsortium.org/entities/<uuid>

1. Call on validation:
{"ingest_metadata": {"dag_provenance_list": [],
                     "files": []},
 "pipeline_message": "",
 "status": ""}
2. Call after derived dataset creation:
{"status": ""}
3. Call after pipeline completes its process:
{"ingest_metadata": {"dag_provenance_list": [],
                     "files": []},
 "pipeline_message": "",
 "status": ""}

We add antibodies, contributors, contacts to the ingest_metadata if those exists in the dataset for call 1 and 3. 

A simple flow will be:
validation(long time)->status update->pipeline for derived dataset triggered->created derived dataset->status update->pipeline processing(long time)->status update.

**Comment by yuanzhou** [comment]
Saw this error in the entity-api logging:
```
[2023-06-13 18:44:30,359] INFO in schema_manager: Cache not found or expired. Making a new HTTP request of GET https://raw.githubusercontent.com/hubmapconsortium/search-api/main/src/search-schema/data/definitions/enums/organ_types.yaml at time 2023-06-13 18:44:30.358998
[2023-06-13 18:44:30,359] INFO in serde: Pickle error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pymemcache/serde.py", line 89, in python_memcache_deserializer
    return unpickler.load()
_pickle.UnpicklingError: invalid load key, 'y'.
[2023-06-13 18:44:30,359] INFO in schema_manager: Cache not found or expired. Making a new HTTP request of GET https://raw.githubusercontent.com/hubmapconsortium/search-api/main/src/search-schema/data/definitions/enums/organ_types.yaml at time 2023-06-13 18:44:30.359268
```

**Comment by yuanzhou** [comment]
Applied a AWS ElastiCache update in case it's a possible cause:
![image](https://github.com/hubmapconsortium/entity-api/assets/195873/2875f86b-1062-4023-be0f-6b4dd861dbcf)

**Comment by yuanzhou** [comment]
Was able to reproduce this behavior using a script that updates the dataset status first, then retrieves the new status via GET calls that uses the cached data. Apparently there are two versions of the cache data. 
<img width="1068" alt="Screenshot 2023-06-17 at 12 02 54 AM" src="https://github.com/hubmapconsortium/entity-api/assets/195873/bcbce6d8-499c-4e85-b026-85507a9132b2">


![image](https://github.com/hubmapconsortium/entity-api/assets/195873/58bafeee-deda-472c-9534-a7140e35d8b2)

**Comment by yuanzhou** [comment]
- Tested against a new Memcached cluster with only 1 node and so far the returned status has been consistent and correct. - Will test again later to be assured. 
- Will submit a support case to AWS and ask them to investigate
