### ISSUE TITLE
Dataset Globus directory lookup

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#49]
Create a lookup function, given a dataset id return the Globus link to the data contained in the dataset.

**Comment by ngehlenborg** [comment]
We need to this in order to show a link to the Globus directory for any data set (both uploaded and HIVE processed data sets).

**Comment by shirey** [comment]
@ngehlenborg @mccalluc 
The plan is to provide the Globus URL for a dataset given the dataset id (can be HuBMAP ID or UUID) via a 307 redirect (maybe should use another redirect code??).  It will optionally take an auth token and send a 403 if the user doesn't have access.  It will redirect to one of three Globus endpoints based on the access level (public, consortium or protected), public only, of course, if no token is provided.  If a dataset isn't found a 404 will be returned.  There is a chance that a 500 can be returned, but not likely under normal circumstances, only for a misconfigred or failing in some way endpoint. 

By returning the URL via a redirect we'll be able to use the service programmatically (javascript or other..) or by directly linking to it and allowing the browser to do the redirect. 

**Inputs**:
- dataset id: The HuBMAP ID (e.g. HBM123.ABCD.456) or UUID
- auth token: (optional) A Globus Nexus token

**Outputs**
- 307 with the Globus Application URL to the datasets's directory
- 404 Dataset not found
- 403 Access Forbidden
- 401 Unauthorized (bad or expired token)

**Comment by ngehlenborg** [comment]
@john-conroy: would that work for the UI?

**Comment by john-conroy** [comment]
Yes, I believe so.

**Comment by mccalluc** [comment]
@shirey :
- I've been burned by permanent redirects that were buggy, so even if the semantics aren't quite right, I think 307 is the better choice. 👍 
- I'm not sure about the value of your returning a 404 or a 403... why not just let Globus handle that? I'd like to just send the users there, and having them land on a 404 that is neither the Portal nor Globus would be odd.
- I'm assuming this will be a POST? Security wise, I don't think it matters, but I think it feels slightly odd to include the credential as a URL parameter. Slightly more work on our end (one-button-form instead of a link) so I might not be making the right call. (ID in URL makes sense.)

I don't think we would access this via JS: We would just left the user go to it directly.

**Comment by shirey** [comment]
@mccalluc I wasn't clear, I expect this to be a GET and token will need to be in Auth header as normal.

A couple reasons for returning codes other than the redirect, mainly usability and lack of with the Globus app, but also I need to check the token to get info from the db to decide which Globus instance it needs to be directed to as we're forced to run a separate endpoints for public access, normal consortium access and high protected data (like human sequence).

**Comment by mccalluc** [comment]
> I wasn't clear, I expect this to be a GET and token will need to be in Auth header as normal.

Oh, ok, then I find returning HTTP status codes weird, but we'll deal with it. Unless I'm mistaken, there's no way for a browser link follow to set arbitrary headers... so this will only be used only by JS, and the default for `fetch` is to [follow redirects](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch)... it can be turned off, but it's another thing to trip over. But tell us when it's ready, and we'll use what you provide.

I believe we'll be hitting this during the initial page render, so the link will be ready and waiting for the user, if they want to go there.

**Comment by mccalluc** [comment]
@ngehlenborg : presentation question... How should the different status codes be rendered? My guess:
- 404: Simply don't show this part of the UI... though this would probably be an error condition? Shouldn't every dataset be represented in Globus, or is that not true?
- 403 Access Forbidden: Some sort of message about contacting the help desk to get access?
- 401 Unauthorized: Apart from rare race conditions (token expires between one API for the entity, and a follow-up API call for the globus) I don't think we'd expect to see this?

**Comment by shirey** [comment]
@mccalluc I get it.  Again, I wasn't clear, the redirect from a browser would only be usable when no token (public only) data is used.  The initial intent of the method was to simply provide the Globus URL to a dataset given a UUID and I've expanded the functionality a bit.  I think switching the return value back to a 200 might be the best thing.

**Comment by mccalluc** [comment]
This is working for us in the portal. Thank! I'll close.
