### ISSUE TITLE
Publication associated Collection

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#498]
Create a new attribute on Publication `associated_collection_uuid` which, on a change via POST/PUT will create a new Neo4j relationship to a Collection of type `[USES_DATA]`  like `(:Publication)-[:IN_PUBLICATION]->(:Collection).

Create an associated attribute on Publication `associated_collection`, filled at GET time only (read-only) which will echo the contents of the Collection referenced by the value in `associated_collection_uuid`.

**Comment by yuanzhou** [comment]
![image](https://github.com/hubmapconsortium/entity-api/assets/195873/dd210f58-466c-4dc0-a775-0826a6550ff4)
