### ISSUE TITLE
Create `/siblings/` endpoint

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#520]
Create a new `/GET siblings/<id>` endpoint that will return the siblings (entities with common direct ancestors/parents).

The endpoint will return, as a json list of entities, the full entity information for all siblings of the specified entity or an empty list if no siblings are found matching the criteria. 

By default the endpoint will return only entities that are the latest versions-- the sibling does not have a newer revision or in Neo4j terms `not (sibling)<-[:REVISION_OF]-(:Entity)`.  This can be overridden by providing the optional argument `?include-old-revisions=true`.

A second optional parameter, `?status=<status>` will constrain the returned siblings to the specified status.  This is used to constrain Dataset siblings to a particular `Dataset.status` value.  If this parameter is provided by default Sample types will be excluded because they do not have a status field.

**Comment by yuanzhou** [comment]
To make things consistent with the `/entities/<id>/tuplets` specified at https://github.com/hubmapconsortium/entity-api/issues/552, we are renaming this siblings call to `/entities/<id>/siblings`. 

I've confirmed with @sunset666 and currently he's not referencing this call in his code, so safe to rename.
