### ISSUE TITLE
Add new `dataset type` attribute

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#521]
Add a new `Dataset.dataset_type`attribute which will eventually replace the existing `data_types` category.

For now, it will be a text/string, not required field, but eventually will be required on POST/create operation.

We can constrain the values to column "D" in the [Pipeline Decision Rules spreadsheet](https://docs.google.com/spreadsheets/d/1aCcGFoTWrBEb2ncN4XiV6rcTqiIf8-jXCpD6azhPPBg/edit#gid=1200505517) PLUS- any of those values followed by a space then square brackets containing any string e.g. `RNASeq [salmon]` or `CODEX [cytokit, image_pyramid]`

Also, (search-api task) add the `Dataset.dataset_type` field to the Elasticsearch indices

**Comment by yuanzhou** [comment]
From @kburke:
>All my Postman tests against TEST are good, under Donor UUID e2df5c01951516e17dbd7c62f357225b
