### ISSUE TITLE
Add `creation_action` specifier on Dataset create

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#533]
For Datasets and Publications add a new transient field used only at create/POST time to set the `creation_action` attribute of the Activity that links the Dataset/Publication to the parent entity or entities.

  - If `creation_action` is not provided at POST time, create the Activity as it is created now with the default `creation_action` field.
  - If a `creation_action` is provided, store that value in the Activity.create_action field.

Currently there is no need to return the `creation_action` on a GET as it will only be used during internal queries.

Currently, allowable values for Dataset/Publication `creation_action` are:

  - "Lab Process"   (derived/processed dataset from a lab)
  - "Central Process" (derived/processed dataset via HIVE processing/pipeline)
  - "Multi-Assay Split" (to designate "secondary" datasets that came from a primary multi-assay dataset)

**Comment by yuanzhou** [comment]
Discussion:

From Zhou:
>Currently Activity.creation_action is an existing property that gets generated automatically on all Activity nodes. So we should

> - either update the logic of set_activity_creation_action() trigger to determine the new creation action for this multi-assay case based on the data types
> - or introduce a new property to indicate this action. Could be a boolean flag.

From Max:
>@yuanzhou I talked with @DerekFurstPitt and @tjmadonna about this. My proposal to them was to add creation_action as a transient property to Dataset and Publication in the provenance schema and then update Activity to remove generated and immutable from the existing creation_action property. Additionally modify set_activity_creation_action to check for that property in the variable existing_data_dict. We will work off of the assumption (as I stated in the diagram above) that creation_action will be a part of the POST's request body to create derived datasets and secondary datasets.

**Comment by yuanzhou** [comment]
@maxsibilla I'm moving the discussion to this card since it's directly relevant. Both solutions will work, adding a new `creation_action` property/attribute to Dataset/Publication then overwrite the `Activity.creation_action` value just seems not necessary if we can handle it directly in the Activity trigger at creation as a one-step event. There may be aspects that I'm not aware of though. So I'm not against the proposed plan.

**Comment by tjmadonna** [comment]
Just a note that if do decide to add the `creation_action` to the post request, we should also add a `before_property_create_validators` to the transient since it's a user defined input that ultimately ends up in the database.

Something like:
```python
def validate_creation_action(property_key, normalized_entity_type, request, existing_data_dict, new_data_dict):
    creation_action = new_data_dict[property_key]
    if creation_action and creation_action not in ["CODCC Process", "Lab Process"]:
        raise ValueError(f"Invalid {property_key} value")
```

**Comment by tjmadonna** [comment]
This is what the proposed changes would look like on the SenNet side.
https://github.com/sennetconsortium/entity-api/commit/f712aacc2752fc9c58a50008dec8dac7c5079b10
