### ISSUE TITLE
Expose `creation_action` attribute from activity on Dataset GET

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#551]
On a `GET /entities/<dataset id>` call, when getting the information for a Dataset entity include the `creation_action` in the response. Unlike all other Dataset attributes `creation_action` is stored in the associated action that represents the creation of that dataset (associated via the ACTIVITY_OUTPUT relationship).

An example Neo4j query that will return the `creation_action` for a Dataset, given the Dataset UUID is:
```
match (ds {uuid:'<dataset uuid>'})<-[:ACTIVITY_OUTPUT]-(a:Activity) return a.creation_action;
```

**Comment by ChuckKollar** [comment]
Using entity_dict['creation_action_activity'] as Entities.Dataset already has a creation_action property which is processed in a different manner see provenance_schema.yaml and code in this file.

**Comment by ChuckKollar** [comment]
Also for Publication.
