### ISSUE TITLE
New `/entities/<entity id>/tuplets` endpoint

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#552]
We need a new endpoint to find the "tuplets" of any given entity.  Tuplets are a sub-set of siblings-- where siblings are all children of the same parent set (or single parent), tuplets are the children created at the same time from the same parent set (or single parent).  In the HuBMAP provenance graph, tuplets can be easily recognized by coming from a common Activity node.

The endpoint should take as an input the id of an entity and return the set of tuplets.  Use the `/entities/<entity id>/siblings` call as a pattern for this and make the responses in the same manner.

This [slide](https://docs.google.com/presentation/d/17_q4v0b-bDOHTxSnsfdT1BmKAxOvQqLdh9jIRtLdpGE/edit?usp=sharing) shows tuplets and siblings.

![image](https://github.com/hubmapconsortium/entity-api/assets/5816400/fa825dd3-90cd-49d3-bcec-66fe140d987f)

**Comment by yuanzhou** [comment]
Addressed via PR https://github.com/hubmapconsortium/entity-api/pull/606
