### ISSUE TITLE
Add public Provenance graph call

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#56]
For the existing entity-api /entities/<identifier>/provenance call, allow public level entities to be returned without an auth token or with a valid, but non-Consortium member's token (no membership in HuBMAP-Read group).  Handle these cases:
 - no token or valid token without HuBMAP-Read membership and requesting access to a public entity, return the provenance graph excluding any consortium level entities (truncate the graph at the level of any non-consortium level entities)
 - no token or valid token without HuBMAP-Read membership and requesting access to a consortium level entity - 403 response
 - valid token with HuBMAP group membership, return full provenance graph (same as current functionality)
 - invalid token- 401 response

**Comment by cborromeo** [comment]
I have pushed changes to two branches in two repos: entity-api and commons.  Both branches are called public_provenance_graph_call.  

Testing process:
I tested using Postman.  I tested with a valid bearer token, no token.  I tested using a dataset with data_access_level set to three settings: consortium, protected, and public.

**Comment by shirey** [comment]
@cborromeo Testing this on STAGE this morning I get a 401 when trying to call without a token and, what I think is a valid, public uuid.  @yuanzhou does this need to to have the setting for "tokenless" authorization through the gateway?
curl https://entity-api.stage.hubmapconsortium.org/entities/211c8835034cbf5414b4aa91de2cc94d/provenance
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.19.1</center>
</body>
</html>

**Comment by yuanzhou** [comment]
@shirey @cborromeo I've made this endpoint public in gateway and redeployed on DEV and STAGE.

**Comment by cborromeo** [comment]
@shirey I just tested it using the curl command you supplied.  it works.  Thanks @yuanzhou !!
