### ISSUE TITLE
Initial schema support of EPIC

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/entity-api#615]
An EPIC is an **E**xternally **P**rocessed **I**ntegrated **C**ollection. These are data that are processed outside of the HIVE (probably by a Data Provider/TMC type group) and provided to us. They would replace the current "Lab Derived" type that we have now.

Add the initial support in schema yaml, and we’ll model these exactly like Publication, where we subclass a Dataset and add any new fields needed (to be specified by Harvard).

EPICs google drive folder put together by the Harvard team: https://drive.google.com/drive/u/0/folders/1hn6RqnZERI5GlFchjbDIdo3UF6A3ct3E

**Comment by shirey** [comment]
This has been finished under different issue(s). Closing,
