### ISSUE TITLE
Move `display_subtype` logic from search-api to entity-api

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/entity-api#631]
Currently this `display_subtype` field gets calculated in the search-api during indexing runtime for each entity (except Collection). By moving the logic to entity-api, we'll be able to take advantage of entity caching thus reduce the number of unnecessary calculations.

**AFTER** implementing the new featured described in #630, add a new field `display_subtype` in schema yaml based on the following rules:

- Donor: fixed value "Donor"
- Upload: fixed value "Data Upload"
- Dataset/Publication:  generated by `on_index_trigger` from `dataset_type` value
- Sample: generated by `on_index_trigger`. When `sample_category == "organ"`, use `organ` code. Otherwise, `capitalize('sample_category')`

**Comment by shirey** [comment]
Won't do this, as it will cause unforeseen downstream issues
