### ISSUE TITLE
New `Upload/Dataset/Publication.status` allowable value `Incomplete`

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#634]
Add the new allowable status value of `Incomplete` for `Dataset.status`, `Publication.status` and `Upload.status` along with the all the existing status allowable values for those entities.  It looks like the change for `Dataset` should affect `Publication` too, as Publication inherits from `Dataset, but `Upload` will need to be handled separately.

**Comment by yuanzhou** [comment]
@ChuckKollar I think there are only two places to support this new status:

https://github.com/hubmapconsortium/entity-api/blob/51949247876c8c84077a6ce62e8d3b5933d4ba79/src/schema/schema_validators.py#L281-L283

Also update the schema yaml description:
https://github.com/hubmapconsortium/entity-api/blob/51949247876c8c84077a6ce62e8d3b5933d4ba79/src/schema/provenance_schema.yaml#L315

**Comment by ChuckKollar** [comment]
Let Jes know when this goes to DEV.

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/entity-api/pull/637
