### ISSUE TITLE
Add attributes to track existing component datasets after conversion to Multi-Assay

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#635]
Add two new attributes to Dataset which will be used to track Multi-Assay datasets that are constructed from existing data:
  - `superseded_associated_processed_component_uuids` array of strings holding the uuids of older Datasets that were used to construct a new Multi-Assay dataset, this will be set on new Multi-Assay datasets
  - `new_associated_multi_assay_uuid` a single string holding the uuid of a new Multi-Assay dataset which was, in part, created using an old/existing dataset.  This will be set on the old, existing component datasets which are "reorganized" into new Multi-Assay datasets.

These new attributes will allow tracking of old existing, processed datasets that are associated with newly created Multi-Assay datasets.  Instead of creating a link/edge in Neo4j we will just store ids in the associated datasets.  This will allow us to track the links shown in yellow in the drawing at the top of [Multi-Assay Reorg](https://docs.google.com/document/d/1e6a2HJzbkLkOHj55bLARWBKaqTAuRxQLd_6P8-CRXPI/edit?usp=sharing)

![image](https://github.com/hubmapconsortium/entity-api/assets/5816400/f643baae-3c11-4573-bf2e-68cbdac910bb)

**Comment by kburke** [comment]
@shirey Should trigger methods do the following?

- Verify no Dataset in the `superseded_associated_processed_component_uuids` array is itself a Multi-Assay Dataset, by verifying none have their own `superseded_associated_processed_component_uuids` array?
- Verify no Dataset in the `superseded_associated_processed_component_uuids` array is already a part of another Multi-Assay Dataset, by verifying none have their `new_associated_multi_assay_uuid` set?

Also, Multi-Assay Datasets can only be POSTed, with all of the component Datasets specified?  There is no notion of PUTting later, particularly to add or delete component Datasets?

**Comment by kburke** [comment]
Per Bill's feedback, I will make sure the Dataset POSTed does not specify both `superseded_associated_processed_component_uuids` and `new_associated_multi_assay_uuid`, but will not navigate submitted UUIDs for deeper verification at this time.

I will limit setting `superseded_associated_processed_component_uuids` to POST call which create a Multi-Assay Dataset, and reject any PUT that modifies it.

POST and PUT calls which set `new_associated_multi_assay_uuid` will only be allowed when  `new_associated_multi_assay_uuid` and `superseded_associated_processed_component_uuids` are not set.
