### ISSUE TITLE
Update to Flask v3.x

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#668]

**Comment by yuanzhou** [comment]
https://flask.palletsprojects.com/en/3.0.x/changes/

**Comment by ChuckKollar** [comment]
Testing criteria is to execute six endpoints:

    GET/PUT/POST on traditional (e.g. app. decorators),
    GET/PUT/POST on a Blueprint decorators

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/entity-api/pull/681
