### ISSUE TITLE
New endpoints (PUT /datasets and PUT /uploads) to handle the bulk updating of entities

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/entity-api#698]
New endpoints (PUT /datasets and PUT /uploads) to handle the bulk updating of entities - https://github.com/sennetconsortium/ingest-api/pull/449/files#diff-dbbd81613f45e75c24d247a0a00eaf8bc018218b14771a16b30b182368852c6e

**Comment by yuanzhou** [comment]
@shirey the original motivation that SenNet started this feature was to support bulk editing in Data Ingest Board for Brendan to update a group of datasets or uploads in one operation. And it's only limited to the fields: `assigned_to_group_name`, `ingest_task`, `status`. 
<img width="1093" alt="Screenshot 2024-07-09 at 11 40 13 PM" src="https://github.com/hubmapconsortium/entity-api/assets/195873/a7d55c3b-7074-4e7f-b95e-dab1b67b4cf7">
<img width="1154" alt="Screenshot 2024-07-09 at 11 37 16 PM" src="https://github.com/hubmapconsortium/entity-api/assets/195873/133ba970-0895-4b4f-87f2-14aed0a95c54">

The two endpoints `PUT /datasets` and `PUT /uploads` added in ingest-api are just as a pass-through, it further calls entity-api by adding the parsed user info for the actual update operations. There's no file system actions so perfectly fine to move to entity-api. 

However, by moving this feature to entity-api, we would eventually want a generic "bulk update" feature--an array of entities to be updated in one single PUT call, regardless of the entity types, and each entity may contain all valid fields. In that context, the Data Ingest Board use case becomes a very small subset where only 3 fields get updated with the same value.

**Comment by shirey** [comment]
Thanks @yuanzhou .   This all sounds correct.  We will build this in entity-api as if it were generic bulk update, but for now we:
  - only accept updates to Dataset and Upload entities
  - only accept updates to the fields:
    - `status`
    - `ingest_task`
    - `assigned_to_group_name`

**Comment by ChuckKollar** [comment]
@shirey I would like some clarification as to how the queuing is to be implemented. The Sennnet code appears to use RQ to implement this. The other option is to use memcache and create a thread that does the processing using memcache as the queue.
I thought that you wanted the latter, but I wanted to confirm.

**Comment by yuanzhou** [comment]
@ChuckKollar when you iterate over the target uuids and make individual `PUT /entities/<uuid>` calls, you can use config https://github.com/hubmapconsortium/entity-api/blob/715c7f65b3107ef0859102f7c74a6dc13352755b/src/instance/app.cfg.example#L38

The main reason we use the PUT call rather than direct neo4j query is because the entity update needs to go through the schema trigger methods and generate corresponding values programmatically before sending over to neo4j. 

The PUT call returns the response immediately while the backend updating may be still going on.

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/entity-api/pull/713
