### ISSUE TITLE
Move `Dataset.dataset_type` validation from `/valueset` to `/dataset-types`

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/entity-api#742]
Currently we handle the `Dataset.dataset_type` validation using this `/valueset` call from UBKG ontology-api:

https://github.com/hubmapconsortium/entity-api/blob/a3b50e02f940ed835ff92f75afd9c3a94d92b515/src/schema/schema_manager.py#L1622-L1628

Move to the new call `/dataset-types?application_context=HUBMAP` for
- They both return the same set of `dataset_type` values, but `/valueset` uses the "term" while `/dataset-types` uses the preferred "dataset_type" field name. 
- The ` /valueset?parent_sab=HUBMAP&parent_code=C003041&child_sabs=HUBMAP` is not as easy to understand without domain knowledge while the `/dataset-types` is a direct fit.
- Also to keep the usage consistent since ingest-ui has moved to use the new call.

**Comment by kburke** [comment]
https://github.com/hubmapconsortium/entity-api/pull/757
