### ISSUE TITLE
Add `Upload.intended_dataset_type` and `Upload.intended_organ` fields

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#765]
Please add two new fields to the Upload entity:

   - `intended_dataset_type`, holds the intended dataset_type for the datasets included in the upload.  It should hold the same code set/value set that is held in `Dataset.dataset_type`
     - type: string
     - indexed: true
     - description: The dataset type of the intended datasets that will be uploaded as part of the Upload.
     - validation: use the same, incomplete, create/update validation scheme (doesn't need to be the same exact shared implementation, if that is hard) that is used for `Dataset.dataset_type`.  We will handle the full, better validation for both this attribute and `Dataset.dataset_type` in a separate card/issue.
   - `intended_organ`, holds the intended organ type that the data in the Upload will be registered against.  It should hold the same code set/value set that is held in `Sample.organ`
     - type: string
     - indexed: true
     - description: The organ code representing the organ type that the data contained in the upload will be registered/associated with.
     - validation: No validation needed.  We will handle proper validation for both this attribute and `Sample.organ` in a separate card/issue.

**Comment by yuanzhou** [comment]
Note, these two fields will be required during creation time. They are also required on the UI side.
